catch (StorageException ex)
{
          Logger.Error(
               string.Format("StorageException caught. {0}. InnerException: {1}", ex.Message,
                    ex.InnerException), ex);
111111111111111111